"""create customers and buildings tables

Revision ID: 42696f3ea5b8
Revises: af4067fb62de
Create Date: 2026-10-02 22:45:18.631007

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "42696f3ea5b8"
down_revision: Union[str, Sequence[str], None] = "af4067fb62de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articles",
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("unit", sa.String(length=50), nullable=False),
        sa.Column("description", sa.String(length=200), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
        ),
        sa.PrimaryKeyConstraint("article_id"),
        sa.UniqueConstraint(
            "customer_id", "article_id", name="uq_articles_customer_article"
        ),
        sa.UniqueConstraint("customer_id", "name", name="uq_articles_customer_name"),
    )
    op.create_index(
        op.f("ix_articles_customer_id"), "articles", ["customer_id"], unique=False
    )
    op.create_table(
        "kit_items",
        sa.Column("kit_item_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("kit_id", sa.Integer(), nullable=False),
        sa.Column("article_id", sa.Integer(), nullable=False),
        sa.Column("target_quantity", sa.Integer(), nullable=False),
        sa.Column("current_quantity", sa.Integer(), nullable=False),
        sa.Column("min_quantity", sa.Integer(), server_default="0", nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("current_quantity >= 0", name="ck_kit_items_current_nonneg"),
        sa.CheckConstraint("min_quantity >= 0", name="ck_kit_items_min_nonneg"),
        sa.CheckConstraint("target_quantity >= 0", name="ck_kit_items_target_nonneg"),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.article_id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id", "article_id"],
            ["articles.customer_id", "articles.article_id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id", "kit_id"],
            ["first_aid_kits.customer_id", "first_aid_kits.kit_id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
        ),
        sa.ForeignKeyConstraint(
            ["kit_id"],
            ["first_aid_kits.kit_id"],
        ),
        sa.PrimaryKeyConstraint("kit_item_id"),
        sa.UniqueConstraint(
            "customer_id", "kit_item_id", name="uq_kit_items_customer_item"
        ),
        sa.UniqueConstraint("kit_id", "article_id", name="uq_kit_items_kit_article"),
    )
    op.create_unique_constraint(
        "uq_pending_intakes_customer_intake",
        "pending_intakes",
        ["customer_id", "pending_intake_id"],
    )

    op.create_index(
        op.f("ix_kit_items_customer_id"), "kit_items", ["customer_id"], unique=False
    )
    op.create_table(
        "stock_movements",
        sa.Column("movement_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("kit_item_id", sa.Integer(), nullable=False),
        sa.Column("pending_intake_id", sa.Integer(), nullable=True),
        sa.Column("delta", sa.Integer(), nullable=False),
        sa.Column("reason", sa.String(length=32), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(source = 'staff' AND created_by IS NOT NULL) OR (source = 'intake' AND created_by IS NULL AND pending_intake_id IS NOT NULL AND reason = 'consumption' AND delta < 0)",
            name="ck_stock_movements_source",
        ),
        sa.CheckConstraint(
            "reason IN ('consumption', 'refill', 'inventory_correction')",
            name="ck_stock_movements_reason",
        ),
        sa.CheckConstraint(
            "source IN ('staff', 'intake')", name="ck_stock_movements_source_values"
        ),
        sa.CheckConstraint("delta <> 0", name="ck_stock_movements_delta_nonzero"),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.User_ID"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id", "kit_item_id"],
            ["kit_items.customer_id", "kit_items.kit_item_id"],
        ),
        sa.ForeignKeyConstraint(
            ["customer_id", "pending_intake_id"],
            ["pending_intakes.customer_id", "pending_intakes.pending_intake_id"],
        ),
        sa.PrimaryKeyConstraint("movement_id"),
    )
    op.create_index(
        op.f("ix_stock_movements_customer_id"),
        "stock_movements",
        ["customer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_movements_kit_item_id"),
        "stock_movements",
        ["kit_item_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_stock_movements_pending_intake_id"),
        "stock_movements",
        ["pending_intake_id"],
        unique=False,
    )
    op.create_index(
        "uq_stock_movements_intake_item",
        "stock_movements",
        ["pending_intake_id", "kit_item_id"],
        unique=True,
        postgresql_where=sa.text("source = 'intake'"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_stock_movements_intake_item",
        table_name="stock_movements",
        postgresql_where=sa.text("source = 'intake'"),
    )
    op.drop_index(
        op.f("ix_stock_movements_pending_intake_id"), table_name="stock_movements"
    )
    op.drop_index(op.f("ix_stock_movements_kit_item_id"), table_name="stock_movements")
    op.drop_index(op.f("ix_stock_movements_customer_id"), table_name="stock_movements")
    op.drop_table("stock_movements")
    op.drop_constraint(
        "uq_pending_intakes_customer_intake", "pending_intakes", type_="unique"
    )
    op.drop_index(op.f("ix_kit_items_customer_id"), table_name="kit_items")
    op.drop_table("kit_items")
    op.drop_index(op.f("ix_articles_customer_id"), table_name="articles")
    op.drop_table("articles")
    # ### end Alembic commands ###
