"""create customers and buildings tables

Revision ID: af4067fb62de
Revises: de9e2a3eda53
Create Date: 2026-10-02 21:58:59.742370

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "af4067fb62de"
down_revision: Union[str, Sequence[str], None] = "de9e2a3eda53"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "buildings",
        sa.Column("building_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("building_name", sa.String(length=100), nullable=False),
        sa.Column("street", sa.String(length=150), nullable=False),
        sa.Column("house_number", sa.String(length=20), nullable=False),
        sa.Column("postal_code", sa.String(length=10), nullable=False),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column(
            "country_code", sa.String(length=2), server_default="DE", nullable=False
        ),
        sa.Column("address_additional", sa.String(length=150), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "country_code ~ '^[A-Z]{2}$'", name="ck_buildings_country_code"
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
        ),
        sa.PrimaryKeyConstraint("building_id"),
        sa.UniqueConstraint(
            "customer_id", "building_id", name="uq_buildings_customer_building"
        ),
        sa.UniqueConstraint(
            "customer_id", "building_name", name="uq_buildings_customer_name"
        ),
    )
    op.create_index(
        op.f("ix_buildings_customer_id"), "buildings", ["customer_id"], unique=False
    )
    op.create_table(
        "first_aid_kits",
        sa.Column("kit_id", sa.Integer(), nullable=False),
        sa.Column("customer_id", sa.Integer(), nullable=False),
        sa.Column("building_id", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=100), nullable=False),
        sa.Column("location_detail", sa.String(length=200), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id", "building_id"],
            ["buildings.customer_id", "buildings.building_id"],
            name="fk_kits_customer_building",
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.customer_id"],
        ),
        sa.PrimaryKeyConstraint("kit_id"),
        sa.UniqueConstraint("customer_id", "kit_id", name="uq_kits_customer_kit"),
        sa.UniqueConstraint("customer_id", "label", name="uq_kits_customer_label"),
    )
    op.create_index(
        op.f("ix_first_aid_kits_building_id"),
        "first_aid_kits",
        ["building_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_first_aid_kits_customer_id"),
        "first_aid_kits",
        ["customer_id"],
        unique=False,
    )
    op.add_column("intake_keys", sa.Column("kit_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "intake_keys", "first_aid_kits", ["kit_id"], ["kit_id"])
    op.add_column(
        "pending_intakes",
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column(
        "pending_intakes",
        "sealed_payload",
        existing_type=sa.String(),
        type_=sa.LargeBinary(),
        existing_nullable=False,
        postgresql_using="decode(sealed_payload, 'base64')",
    )
    op.alter_column(
        "pending_intakes",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "pending_intakes",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.create_index(
        "ix_pending_intakes_inbox",
        "pending_intakes",
        ["customer_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_pending_intakes_intake_key_id"),
        "pending_intakes",
        ["intake_key_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("pending_intakes_resulting_patient_id_fkey"),
        "pending_intakes",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "pending_intakes",
        "patient",
        ["resulting_patient_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "pending_intakes", type_="foreignkey")
    op.create_foreign_key(
        op.f("pending_intakes_resulting_patient_id_fkey"),
        "pending_intakes",
        "patient",
        ["resulting_patient_id"],
        ["id"],
    )
    op.drop_index(
        op.f("ix_pending_intakes_intake_key_id"), table_name="pending_intakes"
    )
    op.drop_index("ix_pending_intakes_inbox", table_name="pending_intakes")
    op.alter_column(
        "pending_intakes",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "pending_intakes",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        nullable=True,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "pending_intakes",
        "sealed_payload",
        existing_type=sa.LargeBinary(),
        type_=sa.String(),
        existing_nullable=False,
        postgresql_using="replace(encode(sealed_payload, 'base64'), E'\\n', '')",
    )
    op.drop_column("pending_intakes", "claimed_at")
    op.drop_constraint(None, "intake_keys", type_="foreignkey")
    op.drop_column("intake_keys", "kit_id")
    op.drop_index(op.f("ix_first_aid_kits_customer_id"), table_name="first_aid_kits")
    op.drop_index(op.f("ix_first_aid_kits_building_id"), table_name="first_aid_kits")
    op.drop_table("first_aid_kits")
    op.drop_index(op.f("ix_buildings_customer_id"), table_name="buildings")
    op.drop_table("buildings")
    # ### end Alembic commands ###
